version: '3'
services:
  pg-db:
    image: postgres:12.10
    restart: always
    environment:
      POSTGRES_PASSWORD: leesti
    ports:
      - 5432:5432
    volumes:
      - pg-data:/Users/abanshin-an/Library/Application Support/Postgres/var-12
volumes:
  pg-data:

#    image: mysql:8.0.23
#    environment:
#      MYSQL_ROOT_PASSWORD: "root"
#    ports:
#      - 3306:3306
#    volumes:
#      - mysql-data:/var/lib/mysql

#volumes:
#  mysql-data:
